### 测试查询所有订单
GET http://localhost:3000/orders
### 新增订单

POST http://localhost:3000/orders
Content-Type: application/json
 
{
  "merchant_id": 1,
    "product_id": 1,
    "quantity": 32,
    "status":"0"
}
### 修改订单状态
PUT http://localhost:3000/orders/2 
Content-Type: application/json
 
{
    "status": "0"
}
### 测试查询所有商品，第一页，每页10个
GET http://localhost:3000/products?page=1&pageSize=10&productName=手机